# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d246b1049631c531f6d994aa0e6e5824e18a0d20c62037986f89dfcdd5a2dda534dbc2f0be5657023e100f074ba83ee0c1bfec91764090a19c850e339a882a0

test:
  secret_key_base: 0bb7e9d4c59ee1f47b90f9122319cea97192879571ca3f03428ddb573bb7fa97320a36b151ae0b1029402fa5dad18833e9295c88873e58e7db66bf082f486b0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
